### ISSUE TITLE
question: what better db to store keys of dozens of bots?

### ISSUE THREAD

**Issue by erickythierry** [deadlinecode/baileys-bottle#23]
Sorry for asking here, but I couldn't find another place.
my doubt is simple. based on your usage, what would be the best DB to store keys for dozens of bots? (80-100 bots)
I tried to use Redis in a scheme I made myself, but the RAM consumption was high (obviously because redis stores everything in ram 😅), so I recently migrated to postgresql, but I had this problem too, high consumption of ram and CPU by the DB (running in a docker container with 2gb ram and 2vcpu, it was using cpu at 100% all the time and ram coming up to 1gb just for the DB)
in redis it was storing something around 200k keys
in postgresql it was already at 100k when it started to consume a lot of hardware resources

Has anyone had any better experience with any specific DB?

**Comment by deadlinecode** [comment]
So first of all you need to understand what you want to save and what not.
If you just have bots that don't need chat message history (or not private ones or not group ones) you can disable them to reduce the load on your DB.

If you have a bot that only responds to current messages you can completly scrap the part where everything chat related gets saved to the db and only save auth session informations.

If you actually need access to all the data that is saved to your db i would recommend spliting your instances.
Not only running multiple instances of your js app or code (because js is single threaded) but also running multiple servers.
This will not only help with balancing the data your js app needs to handle (because lets say one instance of your app so `node index.js` will handle 5 concurrent sessions and you can launch you app multiple times) but it will also reduce the banning risk a lil because multiple servers mean multiple ip's which is less irretating when one ip connects 100 clients to the whatsapp servers.

With that in mind you can basically scale infintely (or until your db can't handle anymore date at which point you need to also multiply your db servers)
I also would recommend a service that handles database scaling for you instead of using the "self hosted db" approach since handling so much data becomes quit expensiv when you self host.
Just google and find a service that suits you. Maybe even one where you pay based on how much data is beeing stored/processed. Should decrease cost in long term and also help with the resource problems

**Comment by deadlinecode** [comment]
@erickythierry 
Hope that answers your question
If not feel free to ask more or hit me up on dc
[deadlinecode#2456](https://discordapp.com/users/330361029366382594)

**Comment by deadlinecode** [comment]
Closing
Feel free to reopen
